"""empty message

Revision ID: 1519f32ad7e2
Revises: e6f01387c645
Create Date: 2019-06-26 03:50:50.562477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1519f32ad7e2'
down_revision = 'e6f01387c645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_manager', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_manager', 'admin')
    # ### end Alembic commands ###
