"""empty message

Revision ID: 52b571990ac1
Revises: 1519f32ad7e2
Create Date: 2019-06-26 14:46:21.856141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52b571990ac1'
down_revision = '1519f32ad7e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_ibfk_1', 'event', type_='foreignkey')
    op.drop_column('event', 'creator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('creator', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('event_ibfk_1', 'event', 'event_manager', ['creator'], ['userid'])
    # ### end Alembic commands ###
