"""empty message

Revision ID: e6f01387c645
Revises: 
Create Date: 2019-06-24 15:27:49.891476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f01387c645'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_manager',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('telnum', sa.String(length=180), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('guest',
    sa.Column('guestid', sa.Integer(), nullable=False),
    sa.Column('displayname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('guestid')
    )
    op.create_table('event',
    sa.Column('eventid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('cost', sa.Float(precision=10), nullable=True),
    sa.Column('venue', sa.String(length=50), nullable=True),
    sa.Column('flyer', sa.Text(), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['event_manager.userid'], ),
    sa.PrimaryKeyConstraint('eventid')
    )
    op.create_table('comment',
    sa.Column('commentid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.String(length=50), nullable=True),
    sa.Column('eventid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eventid'], ['event.eventid'], ),
    sa.PrimaryKeyConstraint('commentid')
    )
    op.create_table('rating',
    sa.Column('rateid', sa.Integer(), nullable=False),
    sa.Column('rate_value', sa.String(length=50), nullable=True),
    sa.Column('eventid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eventid'], ['event.eventid'], ),
    sa.PrimaryKeyConstraint('rateid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('comment')
    op.drop_table('event')
    op.drop_table('guest')
    op.drop_table('event_manager')
    # ### end Alembic commands ###
